spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001

mybatis:
  type-aliases-package: com.guyulong.springcloud.entities
  mapper-locations: classpath:mapper/*.xml

spring:
  profiles: dev
  application:
    name: springcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?servierTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-dept-8001
    prefer-ip-address: true

info:
  app.name: guyulong-springcloud1
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.guyulong.springcloud.entities
  mapper-locations: classpath:mapper/*.xml

spring:
  profiles: test
  application:
    name: springcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?servierTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-dept-8001
    prefer-ip-address: true

info:
  app.name: guyulong-springcloud2
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
